name: Auto Report

on:
  schedule:
    - cron: '0 0 * * 3'  # 每週二的午夜執行
  workflow_dispatch:  # 手動觸發

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # 選擇你需要的 Python 版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test network speed
        run: |
          sudo apt-get update
          sudo apt-get install -y speedtest-cli
          speedtest-cli

      - name: Run script
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          python auto_report.py